### ISSUE TITLE
Too few arguments to function RomanStruk\ManticoreScoutEngine\ManticoreEngine

### ISSUE THREAD

**Issue by ritey** [RomanStruk/manticore-scout-engine#44]
Switching from Meili to Manti using this package but have encountered this issue. Let me know if you need more detail, the specific line is:

`], function ($v, $k) {`

Should $k always be set/have a value? If not would $k = null resolve this issue?

Too few arguments to function RomanStruk\ManticoreScoutEngine\ManticoreEngine::RomanStruk\ManticoreScoutEngine\{closure}(), 1 passed and exactly 2 expected.

romanstruk/manticore-scout-engine/src/ManticoreEngine.php:83

`$topics = Topic::search($this->q)->take(40)->get();`

Topic model is setup.

`    /**
     * Get all Scout related metadata.
     */
    public function scoutMetadata(): array
    {
        return [
            'cutoff' => 0,
            'max_matches' => 1000,
        ];
    }

    public function searchableAs()
    {
        return 'sd_topic_index';
    }

    public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'category_id' => $this->category_id,
        ];
    }`

**Comment by cevin** [comment]
> Switching from Meili to Manti using this package but have encountered this issue. Let me know if you need more detail, the specific line is:
> 
> `], function ($v, $k) {`
> 
> Should $k always be set/have a value? If not would $k = null resolve this issue?
> 
> Too few arguments to function RomanStruk\ManticoreScoutEngine\ManticoreEngine::RomanStruk\ManticoreScoutEngine{closure}(), 1 passed and exactly 2 expected.
> 
> romanstruk/manticore-scout-engine/src/ManticoreEngine.php:83
> 
> `$topics = Topic::search($this->q)->take(40)->get();`
> 
> Topic model is setup.
> 
> ` /** * Get all Scout related metadata. */ public function scoutMetadata(): array { return [ 'cutoff' => 0, 'max_matches' => 1000, ]; }
> 
> ```
> public function searchableAs()
> {
>     return 'sd_topic_index';
> }
> 
> public function toSearchableArray()
> {
>     return [
>         'id' => $this->id,
>         'name' => $this->name,
>         'description' => $this->description,
>         'category_id' => $this->category_id,
>     ];
> }`
> ```

Can you redescribe your problem? What line of which file and what version are you giving an example?
