### ISSUE TITLE
Getting error on creating index

### ISSUE THREAD

**Issue by Faridun1992** [RomanStruk/manticore-scout-engine#50]
public function scoutIndexMigration(): array
    {
        return [
            'fields' => [
                'id' => ['type' => 'bigint'],
                'title' => ['type' => 'text'],
                'subtitle' => ['type' => 'text'],
                'text' => ['type' => 'text'],
                'categories' => ['type' => 'string stored indexed']
            ],
            'settings' => [
                'min_prefix_len' => 3,
                'min_infix_len' => 3,
                'expand_keywords' => 1,
            ],
        ];
    }

getting error 
php artisan manticore:index "App\Models\Post"
SQLSTATE[42000]: Syntax error or access violation: 1064 P03: syntax error, unexpected TEXT, expecting identifier or tablename or MODIFY or TYPE near 'text text, categories string stored indexed) min_prefix_len = '3' min_infix_len =
'3' expand_keywords = '1'' (Connection: manticore, SQL: CREATE TABLE `posts`(id bigint, title text, subtitle text, text text, categories string stored indexed) min_prefix_len = '3' min_infix_len = '3' expand_keywords = '1')

**Comment by RomanStruk** [comment]
I will try to reproduce if the problem exists will be fixed

**Comment by RomanStruk** [comment]
```
public function scoutIndexMigration(): array
{
return [
'fields' => [
'id' => ['type' => 'bigint'],
'title' => ['type' => 'text'],
'subtitle' => ['type' => 'text'],
'text' => ['type' => 'text'], // problem here
'categories' => ['type' => 'string stored indexed']
],
'settings' => [
'min_prefix_len' => 3,
'min_infix_len' => 3,
'expand_keywords' => 1,
],
];
}
```
`
'text' => ['type' => 'text']` conflict in the name of the column
**Try to use a different name**
